# Generated by Django 4.2.7 on 2023-12-03 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vMac', '0003_alter_historicalperformance_date_alter_po_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_orders_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_orders_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 17, 47, 22, 700815)),
        ),
        migrations.AlterField(
            model_name='po',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 17, 47, 22, 700815)),
        ),
    ]
