# Generated by Django 4.2.7 on 2023-12-03 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vMac', '0005_remove_vendor_vendor_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='delivered_at_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalperformance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 18, 30, 47, 329315)),
        ),
        migrations.AlterField(
            model_name='po',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 18, 30, 47, 329315)),
        ),
    ]
