# Generated by Django 4.2.7 on 2023-12-03 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vMac', '0008_alter_historicalperformance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 19, 4, 55, 618781)),
        ),
        migrations.AlterField(
            model_name='po',
            name='delivery_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='po',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 19, 4, 55, 618781)),
        ),
        migrations.AlterField(
            model_name='po',
            name='po_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
